class AppAssets {
  static const String bgImage = 'assets/loginBG.png';
  static const String arrowLeft = 'assets/arrowLeft.png';
  static const String arrowRight = 'assets/arrowRight.png';
  static const String configureBg = 'assets/configureBg.png';
  static const String configureText = 'assets/configureText.png';
  static const String expandIcon = 'assets/expand_icon.png';
  static const String shrinkIcon = 'assets/shrink_icon.png';
  static const String token =
      'eyJhbGciOiJSUzI1NiIsImtpZCI6ImRmOGIxNTFiY2Q5MGQ1YjMwMjBlNTNhMzYyZTRiMzA3NTYzMzdhNjEiLCJ0eXAiOiJKV1QifQ.eyJuYW1lIjoiWWF6aGluaSBNYWxhciBQYXJpIiwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL3dvcmstd2l6YXJkLWJmOTc5IiwiYXVkIjoid29yay13aXphcmQtYmY5NzkiLCJhdXRoX3RpbWUiOjE3MTg4NzM0ODksInVzZXJfaWQiOiJvRnR2RjZlcUtsWkZwak1UTkd3N0JsTEI2TDgyIiwic3ViIjoib0Z0dkY2ZXFLbFpGcGpNVE5HdzdCbExCNkw4MiIsImlhdCI6MTcxODg3MzQ4OSwiZXhwIjoxNzE4ODc3MDg5LCJlbWFpbCI6InlhemhpbmkubWFsYXJAcm9vdHF1b3RpZW50LmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJtaWNyb3NvZnQuY29tIjpbImE1ZDIxMWQ2LWJjNTgtNDcwOS1iZmIzLTI4MWMwZWU4NzFkMCJdLCJlbWFpbCI6WyJ5YXpoaW5pLm1hbGFyQHJvb3RxdW90aWVudC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJtaWNyb3NvZnQuY29tIn19.H7Ts29Yn2CRhgj-uytGXbHXQMcX3hxnGCfwlW_0ajK5n_CihUdp_cTMFdD3CSOr2M2SATm8byx_8YkiJzW9hB8khvJTZo7DIwjErVTjYuSG03AjvaQ3H7y1NOd2IfLQ5HkJfHDPxp5lc1OiotVFnQcrd7oaGMyt3yDvpK5saoEKoXh6wcCOQwzu9OTyJYVNBwrV4bEiVL3RWqzKNBOIhT90Zoljxs21daadpGK5kRqMkySZiU9OqcJqtWyizEWPPIDTSXR7_VHW-a95oJ0mdyVltEn6itU-jJWpwHWJ6mNisRs6_02X6Z_EWcT_PoZCl7vvQv7ERkX1xE-nbGw8XWQ';

}
